name: build-js

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: macos-latest

    outputs:
      PROJECTROOT: ${{ steps.dev.outputs.PROJECTROOT }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Initialization Environment
      id: dev
      run: |
        echo "PROJECTROOT=$PWD" >> $GITHUB_ENV
        echo "::set-output name=PROJECTROOT::$(echo $PWD)"
        brew install coreutils
        npm install

    - name: Check if the git repository is clean
      run: exit $( git status --porcelain --untracked-files=no | head -255 | wc -l )
    - run: npm run lint
    - run: make

    - name: Upload directory
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          ${{ env.PROJECTROOT }}/jitsi-meet.tar.bz2