name: build-android


on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: macos-latest

    outputs:
      PROJECTROOT: ${{ steps.dev.outputs.PROJECTROOT }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Initialization Environment
      id: dev
      run: |
        echo "PROJECTROOT=$PWD" >> $GITHUB_ENV
        echo "::set-output name=PROJECTROOT::$(echo $PWD)"
        brew install coreutils
        npm i -g npm@7
        npm install

    - run: npm run lint

    - run: make

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: cd $PROJECTROOT
    - name: Build Android SDK
      run: ./android/scripts/release-sdk.sh /tmp/repo

    - name: Upload directory
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          ${{ env.PROJECTROOT }}/jitsi-meet.tar.bz2
          /tmp/repo/