name: build-debian

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    outputs:
      PROJECTROOT: ${{ steps.dev.outputs.PROJECTROOT }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Initialization Environment
      id: dev
      run: |
        echo "PROJECTROOT=$PWD" >> $GITHUB_ENV
        echo "::set-output name=PROJECTROOT::$(echo $PWD)"
        sudo apt-get install -y devscripts debhelper nodejs
        npm install -g npm@7
        npm install

    - run: npm run lint

    - run: make

    - run: cd $PROJECTROOT
    - name: Build deb
      run: ./build.sh 20210723 20210723 20210723

    - run: ls -tail
    - name: Upload directory
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          ${{ env.PROJECTROOT }}/jitsi-meet.tar.bz2
          ${{ env.PROJECTROOT }}/jitsi-meet-web_2.0.20210723-1_all.deb
          ${{ env.PROJECTROOT }}/jitsi-meet-tokens_2.0.20210723-1_all.deb
          ${{ env.PROJECTROOT }}/jitsi-meet-turnserver_2.0.20210723-1_all.deb
          ${{ env.PROJECTROOT }}/jitsi-meet-web-config_2.0.20210723-1_all.deb
          ${{ env.PROJECTROOT }}/jitsi-meet-prosody_2.0.20210723-1_all.deb
